ALTER TABLE laps ADD COLUMN IF NOT EXISTS position INTEGER;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS is_personal_best BOOLEAN;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS speed_i1 FLOAT;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS speed_i2 FLOAT;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS speed_fl FLOAT;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS speed_st FLOAT;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS deleted BOOLEAN;
ALTER TABLE laps ADD COLUMN IF NOT EXISTS deleted_reason TEXT;
